version: '3.1'
services:
  mysql:
    image: mysql:5.7
    container_name: container_mysql
    env_file:
      - ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$DB_PASSWORD
      - MYSQL_DATABASE=$DB_NAME
    ports:
      - $DB_PORT:3306

  back-end:
    image: node:latest
    container_name: container_back-end
    # restart: always
    depends_on:
      - mysql
    # env_file:
    #   - ./.env
    ports:
      - 3001:3001
    # environment:
    #   - DB_HOST=mysql
    #   - DB_NAME=$DB_NAME
    #   - DB_USER=$DB_USER
    #   - DB_PASSWORD=$DB_PASSWORD
    #   - SERVER_PORT=$SERVER_PORT
    volumes:
      - ./back_end:/usr/app
    working_dir: /usr/app
    command: bash -c "npm install && npx sequelize db:create && npx sequelize db:migrate && npx sequelize db:seed:all && npm start"

  # front-end:
  #   image: node:latest
  #   container_name: container_front-end
  #   restart: always
  #   depends_on:
  #     - back-end
  #   env_file:
  #     - ./.env
  #   ports:
  #     - $CLIENT_PORT:$CLIENT_PORT
  #   environment:
  #     - REACT_APP_BACK_PORT=$SERVER_PORT
  #     - REACT_APP_BACK_HOST=$SERVER_HOST
  #   volumes:
  #     - ./front-end:/usr/app
  #   working_dir: /usr/app
  #   command: bash -c "npm install && npm start"